/**
 * Posting lifecycle status of a LaundryChargeRecord.
 */
export const LaundryChargeStatus = {
  PENDING_POSTING: 'PENDING_POSTING',
  POSTED: 'POSTED',
} as const;

export type LaundryChargeStatus =
  (typeof LaundryChargeStatus)[keyof typeof LaundryChargeStatus];

export interface LaundryChargeRecordProps {
  id?: string;
  businessChargeId: string;
  transactionId: string;
  garmentLineId: string;
  serviceId: string;
  bracketIndex: number;
  quantity: number;
  unitRate: number;
  totalAmount: number;
  currency?: string;
  calculatedAt: string;
  status?: LaundryChargeStatus;
  financeBillId?: string;
  postedAt?: string;
}

/**
 * LaundryChargeRecord is a Child Entity owned by ServiceAllocation representing
 * a discrete, immutable business charge tranche generated by the BR-L-012 chargeability engine.
 *
 * Invariant:
 * 1. Business charge identity (`businessChargeId`) and commercial calculation fields
 *    (`quantity`, `unitRate`, `totalAmount`) are permanently immutable.
 * 2. Lifecycle state (`status`, `financeBillId`, `postedAt`) tracks Finance posting progress.
 */
export class LaundryChargeRecord {
  public readonly id: string;
  public readonly businessChargeId: string;
  public readonly transactionId: string;
  public readonly garmentLineId: string;
  public readonly serviceId: string;
  public readonly bracketIndex: number;
  public readonly quantity: number;
  public readonly unitRate: number;
  public readonly totalAmount: number;
  public readonly currency: string;
  public readonly calculatedAt: string;

  private _status: LaundryChargeStatus;
  private _financeBillId?: string;
  private _postedAt?: string;

  constructor(props: LaundryChargeRecordProps) {
    if (!props.businessChargeId || props.businessChargeId.trim() === '') {
      throw new Error('LaundryChargeRecord businessChargeId cannot be empty.');
    }
    if (!props.transactionId || props.transactionId.trim() === '') {
      throw new Error('LaundryChargeRecord transactionId cannot be empty.');
    }
    if (!props.garmentLineId || props.garmentLineId.trim() === '') {
      throw new Error('LaundryChargeRecord garmentLineId cannot be empty.');
    }
    if (!props.serviceId || props.serviceId.trim() === '') {
      throw new Error('LaundryChargeRecord serviceId cannot be empty.');
    }
    if (
      typeof props.bracketIndex !== 'number' ||
      props.bracketIndex <= 0 ||
      !Number.isInteger(props.bracketIndex)
    ) {
      throw new Error('LaundryChargeRecord bracketIndex must be a positive integer.');
    }
    if (
      typeof props.quantity !== 'number' ||
      props.quantity <= 0 ||
      !Number.isInteger(props.quantity)
    ) {
      throw new Error('LaundryChargeRecord quantity must be a positive integer.');
    }
    if (typeof props.unitRate !== 'number' || isNaN(props.unitRate) || props.unitRate < 0) {
      throw new Error('LaundryChargeRecord unitRate must be a non-negative number.');
    }
    if (typeof props.totalAmount !== 'number' || isNaN(props.totalAmount) || props.totalAmount < 0) {
      throw new Error('LaundryChargeRecord totalAmount must be a non-negative number.');
    }
    if (!props.calculatedAt || props.calculatedAt.trim() === '') {
      throw new Error('LaundryChargeRecord calculatedAt cannot be empty.');
    }

    this.businessChargeId = props.businessChargeId.trim();
    this.id = props.id?.trim() || this.businessChargeId;
    this.transactionId = props.transactionId.trim();
    this.garmentLineId = props.garmentLineId.trim();
    this.serviceId = props.serviceId.trim();
    this.bracketIndex = props.bracketIndex;
    this.quantity = props.quantity;
    this.unitRate = props.unitRate;
    this.totalAmount = props.totalAmount;
    this.currency = props.currency || 'INR';
    this.calculatedAt = props.calculatedAt;

    this._status = props.status ?? LaundryChargeStatus.PENDING_POSTING;
    this._financeBillId = props.financeBillId;
    this._postedAt = props.postedAt;
  }

  get status(): LaundryChargeStatus {
    return this._status;
  }

  get financeBillId(): string | undefined {
    return this._financeBillId;
  }

  get postedAt(): string | undefined {
    return this._postedAt;
  }

  /**
   * Marks the charge record as POSTED to Finance with the resulting bill ID.
   */
  public markPosted(financeBillId: string, postedAt?: string): void {
    if (!financeBillId || financeBillId.trim() === '') {
      throw new Error('Finance bill ID cannot be empty when marking charge as posted.');
    }
    this._status = LaundryChargeStatus.POSTED;
    this._financeBillId = financeBillId.trim();
    this._postedAt = postedAt ?? new Date().toISOString();
  }

  public toJSON(): LaundryChargeRecordProps {
    return {
      id: this.id,
      businessChargeId: this.businessChargeId,
      transactionId: this.transactionId,
      garmentLineId: this.garmentLineId,
      serviceId: this.serviceId,
      bracketIndex: this.bracketIndex,
      quantity: this.quantity,
      unitRate: this.unitRate,
      totalAmount: this.totalAmount,
      currency: this.currency,
      calculatedAt: this.calculatedAt,
      status: this._status,
      financeBillId: this._financeBillId,
      postedAt: this._postedAt,
    };
  }
}
