export * from './domain';
export * from './application';
export * from './infrastructure';
export * from './components/ResidentHeader';
export * from './components/ResidentQuickActions';
export * from './components/CurrentStaySummaryCard';
export * from './components/ProfileCompletionCard';
export * from './components/OperationalReadinessCard';
export * from './components/PersonalInformationCard';
export * from './components/ContactInformationCard';
export * from './components/AddressCard';
export * from './components/DocumentsCard';
export * from './components/EmergencyContactCard';
export * from './components/VehiclesCard';
export * from './components/DevicesCard';
export * from './components/ResidentIdentityForm';
export * from './components/ResidentsSummaryCards';
export * from './components/ResidentCardItem';
export { ResidentsPage } from './pages/ResidentsPage';
export { default as ResidentWorkspacePage } from './pages/ResidentWorkspacePage';
export * from './services/ResidentLifecycleService';
