export const LaundryExceptionType = {
  MISSING: 'MISSING',
  DAMAGED: 'DAMAGED',
  EXISTING_CONDITION_DISPUTE: 'EXISTING_CONDITION_DISPUTE',
  WRONG_ITEM_RETURNED: 'WRONG_ITEM_RETURNED',
  IDENTITY_DISPUTE: 'IDENTITY_DISPUTE',
  SERVICE_NOT_PERFORMED: 'SERVICE_NOT_PERFORMED',
  SERVICE_NOT_PERFORMED_AS_REQUESTED: 'SERVICE_NOT_PERFORMED_AS_REQUESTED',
  QUALITY_ISSUE: 'QUALITY_ISSUE',
  QUANTITY_DISCREPANCY: 'QUANTITY_DISCREPANCY',
  OTHER: 'OTHER',
} as const;

export type LaundryExceptionType = (typeof LaundryExceptionType)[keyof typeof LaundryExceptionType];
