export const AccountType = {
  ACCOUNTS_RECEIVABLE: 'ACCOUNTS_RECEIVABLE',
  RENT_REVENUE: 'RENT_REVENUE',
  CASH: 'CASH',
  BANK: 'BANK',
  SECURITY_DEPOSIT_LIABILITY: 'SECURITY_DEPOSIT_LIABILITY',
  ADVANCE_CREDIT: 'ADVANCE_CREDIT',
  DAMAGE_RECOVERY: 'DAMAGE_RECOVERY',
  REFUND_PAYABLE: 'REFUND_PAYABLE',
} as const;

export type AccountType = typeof AccountType[keyof typeof AccountType];
